spring:
  application:
    name: nfe-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nfe-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

storage:
  local:
    path: /usr/app
